name: Standards Review

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  standards:
    uses: pattern-labs-foundation/code-standards/.github/workflows/standards-review.yml@2026-09-12-v3  # or main for latest
